### ISSUE TITLE
Owner.cats is populated with objects at the beginning of test #buy_cat

### ISSUE THREAD

**Issue by lovecosma** [learn-co-curriculum/first-mile-getting-started#7]
In this lab, Owner.cats is populated with objects at the beginning of the test. The test is checking for the absence of cats in the array. It seems that the values of a previous test are not clearing for the next test. We examined the heck out of this and even compared with the solution at could not find the reason why.

**Comment by lizbur10** [comment]
I'm closing this since I can't find the lab - sorry Matthew! Please repost if you find it.
